language: python
cache: pip

jobs:
  include:
  - stage: Testing with Python 3.6
    python: '3.6'
    install:
      - pip install -r requirements-dev.txt
      - pip install -e .
    script: python -m pytest
  - stage: Testing with Python 3.7
    pythov codecov
    script:
      - python -m pytest
      - mypy jikanpy
    after_success:
     - pytest --cov jikanpy tests/
     - codecov
